### PR TITLE
Add required checks

### PR DESCRIPTION
**Pull request by joeybaker**

### CODE REVIEW

**Comment by cstumph** [comment]
Makes sense to me, but I wish we could instead mix this onto a base ampersand model or something.

**Comment by Techwraith** [comment]
This is how we'll handle this going forward. We'll do this with the contractor app refactor if we can: https://github.com/Getable/constructable/issues/2661

**Comment by cstumph** [comment]
Oh well then, this almost seems to be making a more of a cleanup task for the future then.

**Comment by cstumph** [comment]
Also, great idea. Been thinking about pretty much exactly that quite a bit lately.

**Comment by joeybaker** [comment]
Yea… this is true. But this starts enforcing good practices now so that the cleanup will be as easy as find/replace instead of find-all-places-that-aren't-passing-required-props.

**Comment by joeybaker** [comment]
So… yay/nay on merging? @Techwraith @cstumph ?

**Comment by cstumph** [comment]
Yay.

**Comment by joeybaker** [comment]
@Techwraith concurs too. Merging

**Pull request merged**
