### PR TITLE
react template: remove entry css

### PR DESCRIPTION
**Pull request by joeybaker**
We don’t need the entry css, because we can bake it into our dev html.

### CODE REVIEW

**Comment by joeybaker** [comment]
@cstumph says :+1:

**Comment by cstumph** [comment]
No I said: 😐Which is equidistant between yes and no.

**Comment by jmcelroy5** [comment]
:+1:

**Comment by tedbreen** [comment]
:+1:

**Comment by joeybaker** [comment]
Cool. We have a quorum and this has been up a while. Merging.

**Pull request merged**
